name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v2
      with:
        username: soichisumi
        password: ${{ secrets.DOCKER_PASSWORD }}
        image_name: soichisumi0/slack-janken
